name: Docker CI Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/docker/Dockerfile"

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198e19c3bc3c30 # v6.18.0
        with:
          context: .github/docker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-ci:6.0.1
            ghcr.io/${{ github.repository }}-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
